### ISSUE TITLE
Planering

### ISSUE THREAD

**Issue by johnsson84** [johnsson84/HealthCareAB#1]
- [x] Skapa repo
- [x] Skapa git board
- [x] Risk analys #21 
- [x] Sätta upp issues för sprint 1 och 2
- [x] Fixat LoFi #2 
- [x] Fixa bättre beskrivning på PRIO 1

**Comment by NybergViktor** [comment]
![Image](https://github.com/user-attachments/assets/d1a0fb77-709b-41c0-86bf-911fdb877685)

**Comment by NybergViktor** [comment]
[prod_lev_mjukvara_projekt.pdf](https://github.com/user-attachments/files/18183825/prod_lev_mjukvara_projekt.pdf)
